CREATE TABLE public.weather (
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    temperature float8,
    created_date timestamp NULL,
    modified_date timestamp NULL,
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
